image: harbor.repo.admxj.cn/library/mvn-jdk8:jdk8-3.6.3-v1.0

default-job:
  script:
    - mvn test -U
  except:
    - tags

release-job:
  script:
    - mvn package -U
  artifacts:
    paths:
      - target/*.war
  only:
    - tags
