image: harbor.repo.admxj.cn/library/mvn-jdk8:jdk8-3.6.3-v1.0

# 定义 stages
stages:
  - test
  - build


test:
  stage: test
  script:
    - mvn test -U
  tags:
    - maven-node

release-job:
  stage: build
  script:
    - mvn package -U
  artifacts:
    paths:
      - target/*.war
  tags:
    - maven-node
